import {
  Card,
  Box,
  Image,
  Text,
  Flex
} from '@chakra-ui/react'
import { User } from '@prisma/client'
import Head from 'next/head'
import { GetServerSideProps } from 'next/types'
import prisma from '../../utils/prisma'

/**
   * This page shows the current logged in user's profile.
   * 
   *
   * @param props - This is an object containing a user's profile.
   * 
   * @returns A React Component containing a user's profile.
   *
   */
export default function Profile({ user } : { user: User }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex justifyContent="center" width="100%" my="8rem">
        <Box width={["100%", "70%", "50%", "40%"]} mx={[0, 4, 8, 12]}>
          <Box display="flex" alignItems="baseline">
              <Text fontSize='5xl' as="b" mt={8}>
                {user.firstName} {user.lastName}
              </Text>
            </Box>

            <Box>
              <Text fontSize="large">{user.email}</Text>
            </Box>
            <Box mt={4}>
              <Text as="p">Contact Number: {user.contactNumber}</Text>
            </Box>
        </Box>
      </Flex>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { params } = context
  
  // If no params are passed, redirect to home page
  if (!params) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      }
    }
  }

  // Email is required
  if (!('email' in params)) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      }
    }
  }

  const email = params.email

  // Get the user from the database
  const user = await prisma.user.findUnique({
    where: {
      email: email as string
    },
  })

  if (user) {
    return {
      props: {
        user
      },
    }
  }

  return {
    notFound: true
  }
}