import {
  Box,
  Text
} from '@chakra-ui/react'
import { Hotel, Photo } from '@prisma/client';
import Head from 'next/head'
import { GetServerSideProps } from 'next/types';
import Hero from '../components/Home/Hero'
import HotelList from '../components/HotelList';
import prisma from '../utils/prisma';

/**
   * This page shows recommended hotels.
   * The recommended hotels are the hotels with the highest ratings.
   * 
   *
   * @param props - This is an object containing the hotels' information.
   * 
   * @returns A React Component containing the index page.
   *
   */
export default function Home({ recommendedHotels }: { recommendedHotels: (Hotel & {photos: Photo[]})[] }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />

      <Box p={16} mt={8}>
        <Text fontSize='5xl' as="b" mb={8}>
          Recommended Hotels
        </Text>

        <HotelList hotels={recommendedHotels.map(hotel => ({
          id: hotel.id,
          name: hotel.name,
          image: hotel.photos[0] ? `/api/photos/${hotel.photos[0].id}` : "https://picsum.photos/id/57/1280/720/?grayscale&blur=10",
          location: hotel.location,
          rating: hotel.totalRating.toFixed(2),
          price: `From \$${hotel.minPrice.toFixed(2)} per night`
        }))} />
      </Box>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  // Get the recommended hotels
  const recommendedHotels = await prisma.hotel.findMany({
    include: {
      photos: true,
    },
    orderBy: [
      {
        totalRating: 'desc',
      }
    ],
    take: 6,
  })

  return {
    props: {
      recommendedHotels
    },
  }
}